apiVersion: v1
kind: Service
metadata:
  name: 
  labels:
    run: ft_server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: ft_server
