apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps 
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: NodePort
  ports:
  - port: 20
    protocol: TCP
    name: 20-ftps
  - port: 21
    protocol: TCP
    name: ftps
  selector:
    app: ftps
