apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: nginx.ft-services
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: grafana.ft-services
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
  - host: phpmyadmin.ft-services
    http:
      paths:
      - backend:
          serviceName: phpmyadmin
          servicePort: 5000
  - host: wordpress.ft-services
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 5050
