apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress 
  labels:
    app: wordpress
    label: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
